name: Build Taskbar Groups

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Install .NET Core SDK
      run: choco install dotnetcore-sdk

    - name: Install required workloads
      run: |
        choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools --add Microsoft.VisualStudio.Workload.NetCoreBuildTools --includeRecommended --includeOptional"

    - name: Restore NuGet packages
      run: nuget restore TaskbarGroups.sln

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: msbuild TaskbarGroups.sln /p:Configuration=Release

    - name: Publish
      run: dotnet publish --configuration Release --output ./publish
